server:
  hostname: localhost
  port: 9200

spring:
  application:
    name: maeng-lobby-service
  cloud:
    config:
      name: maeng
      profile: lobby

eureka:
  client:
    service-url:
      defaultZone: http://${server.hostname}:8761/eureka/
  instance:
    hostname: ${server.hostname}