server:
  hostname: maengland.com
  port: 9600

eureka:
  client:
    service-url:
      defaultZone: http://${server.hostname}:8761/eureka/

spring:
  config:
    import: configserver:http://${server.hostname}:8880
  application:
    name: maeng-gateway-service
  cloud:
    config:
      name: maeng
      profile: gateway
  security:
    enabled: false



  main:
    allow-bean-definition-overriding: true
logging:
  level:
    root: info