server:
  hostname: manegland.com
  port: 9600

eureka:
  client:
    service-url:
      defaultZone: http://${server.hostname}:8761/eureka/

spring:
    import: configserver: http://${server.hostname}:8880
  application:
    name: apigateway-service
  cloud:
    config:
      name: maeng
      profile: gateway

  main:
    allow-bean-definition-overriding: true
jwt:
  secret-key: aodaodrpdlafosemrlawldudrlatkdrmstjgusejrtlalswntladmswlsdldlfgh208zjstjftlcldhodhkTslwoaldjqtdj
