server:
  hostname: maengland.com
  port: 9600


spring:
  config:
    import: configserver:http://${server.hostname}:8880
  application:
    name: maeng-gateway-service
  cloud:
    config:
      name: maeng
      profile: gateway
  main:
    allow-bean-definition-overriding: true

eureka:
  client:
    service-url:
      defaultZone: http://${server.hostname}:8761/eureka/
  instance:
    hostname: ${server.hostname}