server:
  hostname: localhost
  port: 9230

spring:
  application:
    name: maeng-gsb-service
  cloud:
    config:
      name: maeng
      profile: gsb

eureka:
  client:
    service-url:
      defaultZone: http://${server.hostname}:8761/eureka/
  instance:
    hostname: ${server.hostname}