export const images = {
  common: {
    header: {
      bronzeFrame: '/images/common/frame-bronze.png',
      silverFrame: '/images/common/frame-silver.png',
      goldFrame: '/images/common/frame-gold.png',
      challengerFrame: '/images/common/frame-challenger.png',
      setting: '/images/common/ic-setting.png',
      friends: '/images/common/ic-friend.png',
      dummyProfile: '/images/common/dummyProfile.png',
      alarm: '/images/common/ic-alarm.png',
      back: '/images/common/ic-arrow-back.png',
      timer: '/images/common/ic-timer.png',
    },
    leftArrow: '/images/common/ic-left-arrow.png',
  },
  index: {
    background: '/images/index/background-index.png',
    icon: '/images/index/ic-main.png',
    donwloadComplete: '/images/index/ic-download-complete.png',
  },
  waitingRoom: {
    header: {
      lock: '/images/common/ic-lock.png',
      unlock: '/images/common/ic-unlock.png',
    },
    dummyRabbit: '/images/waitingRoom/dummyRabbit.png',
    info: '/images/waitingRoom/ic-info.png',
    crown: '/images/waitingRoom/ic-crown.png',
    ready: '/images/waitingRoom/ic-ready.png',
    inactive: '/images/waitingRoom/inactive.png',
  },
  home: {
    discription: '/images/home/ic-discription.png',
    gsb: '/images/home/gsb.png',
    jwac: '/images/home/jwac.png',
    awrsp: '/images/home/awrsp.png',
  },
  lobby: {
    close: '/images/lobby/ic-close-modal.png',
  },
  gsb: {
    allChipsBet: '/images/gsb/all-chips-bet.png',
    background: '/images/gsb/background.png',
    goldStar: '/images/gsb/gold-star.png',
    silverStar: '/images/gsb/silver-star.png',
    bronzeStar: '/images/gsb/bronze-star.png',
    chip: '/images/gsb/chip.png',
    chips: '/images/gsb/chips.png',
    cardBack: '/images/gsb/card-back.png',
    cardFrontHu: '/images/gsb/card-front-hu.png',
    cardFrontSun: '/images/gsb/card-front-sun.png',
    mul: '/images/gsb/ic-x.png',
  },
  awrsp: {
    background: '/images/awrsp/background.png',
    scissorsCard: '/images/awrsp/scissors-card.png',
    scissorsDrawCard: '/images/awrsp/scissors-draw-card.png',
    rockCard: '/images/awrsp/rock-card.png',
    rockDrawCard: '/images/awrsp/rock-draw-card.png',
    paperCard: '/images/awrsp/paper-card.png',
    paperDrawCard: '/images/awrsp/paper-draw-card.png',
    roundDisplay: '/images/awrsp/round-display.png',
    history: '/images/awrsp/ic-history.png',
  },
  gameRoom: {
    jwac: {
      backGround: '/images/gameRoom/background-jwac.png',
      table: '/images/gameRoom/table.png',
      money: '/images/gameRoom/ic-money.png',
      roundFrame: '/images/gameRoom/frame-round.png',
      noteFrame: '/images/gameRoom/frame-note.png',
      showCase: '/images/gameRoom/showcase.jpg',
      diamond: '/images/gameRoom/diamond.png',
      emerald: '/images/gameRoom/emerald.png',
      ruby: '/images/gameRoom/ruby.png',
      sapphire: '/images/gameRoom/sapphire.png',
      checkIcon: '/images/gameRoom/ic-check-item.png',
      jewelryInfomationFrame: '/images/gameRoom/frame-jewelry-infomation.png',
      backWhite: '/images/gameRoom/ic-back-white.png',
      jewelryInfomation: '/images/gameRoom/jewelry-infomation.png',
    },
  },
  user: {
    back: '/images/user/ic-arrow-left.png',
    camera: '/images/user/ic-camera.png',
    edit: '/images/user/ic-edit.png',
    submit: '/images/user/ic-submit.png',
  },
}
