server:
  hostname: localhost
  port: 9110

spring:
  application:
    name: maeng-auth-service
  cloud:
    config:
      name: maeng
      profile: auth

eureka:
  client:
    service-url:
      defaultZone: http://${server.hostname}:8761/eureka/
  instance:
    hostname: ${server.hostname}