server:
  hostname: localhost
  port: 9220

spring:
  application:
    name: maeng-jwac-service
  cloud:
    config:
      name: maeng
      profile: jwac

eureka:
  client:
    service-url:
      defaultZone: http://${server.hostname}:8761/eureka/
  instance:
    hostname: ${server.hostname}