server:
  hostname: maengland.com
  port: 9120

spring:
  config:
      import: configserver:http://${server.hostname}:8880
  application:
    name: maeng-user-service
  cloud:
    config:
      name: maeng
      profile: user

eureka:
  client:
    service-url:
      defaultZone: http://${server.hostname}:8761/eureka/
  instance:
    hostname: ${server.hostname}