server:
  hostname: maengland.com
  port: 9120

spring:
  config:
      import: configserver:http://${server.hostname}:8880
  application:
    name: maeng-user-service
  cloud:
    config:
      name: maeng
      profile: user
  datasource:
    url: jdbc:mysql://${server.hostname}:3306/maengland?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: maeng
    password: maengmaeng
  redis:
    host: ${server.hostname}
    port: 6379
    password: maengmaeng


eureka:
  client:
    service-url:
      defaultZone: http://${server.hostname}:8761/eureka/
  instance:
    hostname: ${server.hostname}
logging:
  level:
    root: info